Fix fail to build with glibc 2.43
Glibc 2.43 comes with '#define _XOPEN_SOURCE 800' which causes the
following errors:

In file included from utmp.c:31:
../../src/snoopy.h:31:10: error: '_XOPEN_SOURCE' redefined [-Werror]
   31 | #define  _XOPEN_SOURCE   700
      |          ^~~~~~~~~~~~~
In file included from /usr/include/utmp.h:21,
                 from utmp-snoopy.h:27,
                 from utmp.c:26:
/usr/include/features.h:234:10: note: this is the location of the previous definition
  234 | # define _XOPEN_SOURCE  800
      |          ^~~~~~~~~~~~~

domain.c: In function 'snoopy_datasource_domain':
domain.c:126:17: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  126 |         hashPtr = strchr(linePtr, '#');
      |                 ^

This patch guards the '#define  _XOPEN_SOURCE   700' in snoopy.h and
drops the 'const' qualifier from the variable 'linePtr' resulting in
building snoopy successfully using glibc 2.43.